### ISSUE TITLE
Error output for drives having not enough size - can we show -h sizes, and small wording improvement

### ISSUE THREAD

**Issue by scottdarrah** [swimlane/swimlane-environment-validator#10]
if your drives aren't to spec, the output before the chart shows up looks like this:

{lib/verify_disk_space.py:43} ERROR - /var/openebs has less 322122547200 bytes available.
{lib/verify_disk_space.py:43} ERROR - /var/lib/docker has less 107374182400 bytes available.

can that be human readable? 

also, what is 'has less xxx bytes available' trying to say? has that many less bytes than the recommended size or has less than that many bytes?

**Comment by bagel-dawg** [comment]
@scottdarrah I've adjusted the check to show some nicer sizes, however `df -h` doesn't necessarily check number of _bytes_, but instead the number of _blocks_, which is ultimately a semantics game. I bring this up because we will now check that the size of the partition is "around or about" the required size, plus or minus ~5GB.

Is that acceptable?

**Comment by scottdarrah** [comment]
plus or minus 5 gig is a little too lenient perhaps...?

**Comment by scottdarrah** [comment]
how about like 100 meg? that seems like almost reasonable margin of error on drive sizes this large?
